### ISSUE TITLE
Missing cmd folder

### ISSUE THREAD

**Issue by teejaded** [admiralobvious/tinysyslog#3]
This folder `cmd/tinysyslogd` doesn't exist.

https://github.com/alexferl/tinysyslog/blob/master/Makefile#L15

Your .gitignore seems to have prevented you from committing it.

https://github.com/alexferl/tinysyslog/blob/master/.gitignore#L28

**Comment by huanghuazhang** [comment]
As a work around, just checkout tag v0.2.0

**Comment by alexferl** [comment]
Sorry I never got noticed this issue was opened, this is fixed in the latest release.
