### ISSUE TITLE
help request: Is there a path that I can volume for the log files?

### ISSUE THREAD

**Issue by AmerDwight** [admiralobvious/tinysyslog#6]
As I can set parameters of filesystem module in Configurations
But I didn't find the path that I can point to with docker volume
Or is there a way to pull the log files out?

**Comment by alexferl** [comment]
I'm not sure what you mean, a Docker volume is just mounted at the path you specify in the container so if you set the `--sink-filesystem-filename` setting you can set it to that same path.
```
docker run -p 5140:5140/udp --mount source=myvol2,target=/logs --rm tinysyslog --sinks=filesystem,console --sink-filesystem-filename=/logs/syslog.log
```
And then wherever the volumes are stored on your Docker host:
```
/var/lib/docker/volumes/myvol2/_data # ls
syslog.log
/var/lib/docker/volumes/myvol2/_data # cat syslog.log
Jan  1 12:01:21 hostname appname[1234]: message
Jan  1 12:01:21 hostname appname[1234]: message
Jan  1 12:01:21 hostname appname[1234]: message
```

**Comment by AmerDwight** [comment]
Nice to have your response.

I thought --sink-filesystem-filename were set to  indicate just "file name"
I didn't realize I can put path to point it.
Thanks a lot!!
It's a quite useful log server by the way.
